# Generated by Django 4.0 on 2023-05-25 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationforreading',
            name='reader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='publicationcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
        ),
        migrations.AddField(
            model_name='publicationcomment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='publications.publication'),
        ),
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='users.customuser', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='publication',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='publication',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='users.customuser', verbose_name='Рецензент'),
        ),
        migrations.AddField(
            model_name='publication',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='publications.Tag', verbose_name='Тэги'),
        ),
    ]
